import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#fcecea",
        "outline-variant": "#e5e2df",
        "on-primary-fixed": "#ffffff",
        "inverse-surface": "#1c1b1a",
        "on-error": "#ffffff",
        "surface-container": "#f7f3f0",
        "on-error-container": "#560004",
        "surface-container-low": "#fdf9f6",
        background: "#fdf9f6",
        "surface-tint": "#560004",
        "on-secondary": "#ffffff",
        "secondary-dim": "#7d6d6a",
        "surface-container-highest": "#e5e2df",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#001d33",
        primary: "#560004",
        tertiary: "#004a77",
        "on-primary-container": "#410002",
        "on-secondary-fixed": "#2c1a17",
        "surface-bright": "#fffbff",
        "on-secondary-fixed-variant": "#5a4441",
        "on-tertiary-fixed-variant": "#004a77",
        "tertiary-fixed-dim": "#a2c9ff",
        "surface-container-high": "#f1edea",
        secondary: "#745b57",
        surface: "#fdf9f6",
        "tertiary-fixed": "#d1e4ff",
        "primary-dim": "#ffb4ab",
        "tertiary-container": "#d1e4ff",
        "on-primary-fixed-variant": "#93000a",
        outline: "#857371",
        "inverse-on-surface": "#fdf9f6",
        "on-tertiary": "#ffffff",
        "on-background": "#1c1b1a",
        "surface-dim": "#e1ddd9",
        "primary-fixed-dim": "#ffb4ab",
        "primary-fixed": "#ffdad6",
        "surface-variant": "#f5dedb",
        "secondary-fixed-dim": "#e3bdb7",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1c1b1a",
        "error-container": "#ffdad6",
        "on-secondary-container": "#2b1614",
        "on-surface-variant": "#534341",
        "inverse-primary": "#ffb4ab",
        "error-dim": "#ffb4ab",
        "on-tertiary-container": "#001d33",
        "secondary-fixed": "#ffdad6",
        error: "#ba1a1a",
        "secondary-container": "#ffdad6",
        "tertiary-dim": "#a2c9ff",
      },
      borderRadius: {
        DEFAULT: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-epilogue)", "sans-serif"],
        body: ["var(--font-public-sans)", "sans-serif"],
        label: ["var(--font-public-sans)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
